#!/usr/bin/env bash
#
# This file is part of my installation files
# Copyright © 2017 seamus tuohy, <code@seamustuohy.com>
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the included LICENSE file for details.


get_git_package() {
    local package_dir="${1}"
    local repo="${2}"
    if [[ ! -e $package_dir ]]; then
        git clone "$repo"  "$package_dir"
    else # Update to the latest version for good measure.
        git --git-dir="$package_dir"/.git --work-tree="$package_dir"  pull
    fi
}

pip3_install() {
    local package="${1}"
    local installed=$(pip3 list \
                             | grep -E "^${package}\s\([0-9\.]*\)$" \
                             | grep -o "${package}")
    if [[ "${installed}" = ""  ]]; then
        echo "Installing ${package} via python pip 3"
        sudo pip3 install "${package}"
        echo "Installation of ${package} completed."
    else
        echo "${package} already installed in pip3. Skipping...."
    fi
}

pip_install() {
    local package="${1}"
    local installed=$(pip list \
                             | grep -E "^${package}\s\([0-9\.]*\)$" \
                             | grep -o "${package}")
    if [[ "${installed}" = ""  ]]; then
        echo "Installing ${package} via python pip"
        sudo pip install "${package}"
        echo "Installation of ${package} completed."
    else
        echo "${package} already installed in pip. Skipping...."
    fi
}

check_command_installed() {
    local command=$1
    if [[ 1 == $(type $command 2> /dev/null; echo $?) ]]; then
        echo "${command}: False"
    else
        echo "${command}: True"
    fi
}
